### ISSUE TITLE
Problem with arabic subtitles

### ISSUE THREAD

**Issue by Tizioincognit0** [aronkst/srt_translator#1]
When I try to translate an arabic subtitle into another language (e.g. Italian) I got theese error messages.
I’m using Python 3.6 on macOS 10.14.6 Mojave. This only happens with Arabic subtitles.
````
Traceback (most recent call last):
  File "/Applications/SRT Translator/srt_translator.py", line 52, in <module>
    dest=language_to_translate)
  File "~/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "~/anaconda3/lib/python3.6/site-packages/googletrans/client.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "~/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "~/anaconda3/lib/python3.6/site-packages/googletrans/utils.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "~/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "~/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Tizioincognit0** [comment]
I discovered that, If I use “python3” instead of “python” at the beginning of the command, SRT Translator makes a partial translation and doesn’t give any error.

**Comment by Tizioincognit0** [comment]
I discovered that, If I use “python3” instead of “python” at the beginning of the command, SRT Translator makes a partial translation and doesn’t give any error.

**Comment by Tizioincognit0** [comment]
I discovered that, If I use “python3” instead of “python” at the beginning of the command, SRT Translator makes a partial translation and doesn’t give any error.

**Comment by Tizioincognit0** [comment]
I discovered that, If I use “python3” instead of “python” at the beginning of the command, SRT Translator makes a partial translation and doesn’t give any error.

**Comment by Tizioincognit0** [comment]
I discovered that, If I use “python3” instead of “python” at the beginning of the command, SRT Translator makes a partial translation and doesn’t give any error.

**Comment by aronkst** [comment]
Hello,

For some reason Google was not translating texts with up to 5000 characters, it reduced the size to 2500 and performing a test worked. I performed a commit to the master with this change (https://github.com/aronkst/srt_translator/commit/d534fb6676214866d3abaa9c66c72ed2de263bd9), could you test it?

**Comment by Tizioincognit0** [comment]
I tested it and now the Arabic translation is complete.
